-   repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
    - id: black
    python_version: python3.6

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: trailing-whitespace
      exclude: ^channelstream/static/
    - id: check-case-conflict
    - id: check-merge-conflict
    - id: check-symlinks
    - id: end-of-file-fixer
      exclude: ^channelstream/static/
    - id: debug-statements
    - id: requirements-txt-fixer
